# Generated by Django 4.0.3 on 2022-04-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='engmail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='mail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
